import type { ElementType } from "../types/form.types";

export const SUPPORTED_ELEMENT_TYPES = new Set<ElementType>([
  "short_text",
  "long_text",
  "number",
  "email",
  "phone",
  "dropdown",
  "radio",
  "checkbox",
  "date",
  "time",
  "rating",
  "likert",
  "matrix",
  "scale",
  "file_upload",
  "signature",
  "image",
  "video",
  "boolean",
  "section_header",
]);

export const PROPERTY_SUPPORT: Record<string, Set<ElementType>> = {
  required: new Set([
    "short_text",
    "long_text",
    "number",
    "email",
    "phone",
    "dropdown",
    "radio",
    "checkbox",
    "date",
    "time",
    "rating",
    "likert",
    "matrix",
    "scale",
    "file_upload",
    "signature",
    "boolean",
  ]),
  visible: new Set([
    "short_text",
    "long_text",
    "number",
    "email",
    "phone",
    "dropdown",
    "radio",
    "checkbox",
    "date",
    "time",
    "rating",
    "likert",
    "matrix",
    "scale",
    "file_upload",
    "signature",
    "image",
    "video",
    "boolean",
    "section_header",
  ]),
  placeholder: new Set(["short_text", "long_text", "number", "email", "phone"]),
  maxLength: new Set(["short_text", "long_text"]),
  default: new Set([
    "short_text",
    "long_text",
    "number",
    "email",
    "phone",
    "dropdown",
    "radio",
    "checkbox",
    "date",
    "time",
    "rating",
    "scale",
    "boolean",
  ]),
  min: new Set(["number", "scale"]),
  max: new Set(["number", "scale"]),
  step: new Set(["number", "scale"]),
  integerOnly: new Set(["number"]),
  options: new Set(["dropdown", "radio", "checkbox"]),
  allowOther: new Set(["dropdown", "radio"]),
  searchable: new Set(["dropdown"]),
  minSelected: new Set(["checkbox"]),
  maxSelected: new Set(["checkbox"]),
  includeTime: new Set(["date"]),
  minDate: new Set(["date"]),
  maxDate: new Set(["date"]),
  minTime: new Set(["time"]),
  maxTime: new Set(["time"]),
  stepMinutes: new Set(["time"]),
  scale: new Set(["rating"]),
  labels: new Set(["rating"]),
  icon: new Set(["rating"]),
  statements: new Set(["likert"]),
  scaleLabels: new Set(["likert"]),
  requiredPerStatement: new Set(["likert"]),
  rows: new Set(["matrix", "long_text"]),
  columns: new Set(["matrix"]),
  cellType: new Set(["matrix"]),
  requiredPerRow: new Set(["matrix"]),
  minLabel: new Set(["scale"]),
  maxLabel: new Set(["scale"]),
  allowedTypes: new Set(["file_upload"]),
  maxFiles: new Set(["file_upload"]),
  maxSizeMB: new Set(["file_upload"]),
  captureMode: new Set(["signature"]),
  src: new Set(["image", "video"]),
  alt: new Set(["image"]),
  width: new Set(["image", "video"]),
  height: new Set(["image", "video"]),
  caption: new Set(["image", "video"]),
  onLabel: new Set(["boolean"]),
  offLabel: new Set(["boolean"]),
  title: new Set(["section_header"]),
  subtitle: new Set(["section_header"]),
};

export function isPropertySupportedForType(
  property: string,
  type: ElementType,
): boolean {
  const supportedTypes = PROPERTY_SUPPORT[property];
  if (!supportedTypes) return false;
  return supportedTypes.has(type);
}
